CREATE TABLE BOOKMANGER.AUTOS (
  ID INT NOT NULL  AUTO_INCREMENT,
  AUTO_NAME VARCHAR(255) NOT NULL,
  AUTO_COLOR VARCHAR(255) NOT NULL,
  AUTO_POWER INT NOT NULL,
  AUTO_WEIGHT INT NOT NULL,
  AUTO_PRICE INT NOT NULL,
  PRIMARY KEY (ID));